# Generated by Django 5.1 on 2024-09-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecomment',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_note', to='core.note'),
        ),
    ]
