# Generated by Django 5.1 on 2024-10-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notefavorite_notelike_subscription'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notelike',
            old_name='post',
            new_name='note',
        ),
        
    ]
