# Generated by Django 5.1 on 2024-10-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_post_notelike_note_notefavorite'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Автор цитат',
                'verbose_name_plural': 'Авторы цитат',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка на мудреца', 'verbose_name_plural': 'Подписки на мудреца'},
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, default='Автор неизвестен', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note_author', to='core.author'),
        ),
        migrations.CreateModel(
            name='NoteFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_favorites', to='core.note')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_favorites', to='user.profile')),
            ],
            options={
                'verbose_name': 'Избраная цитата',
                'verbose_name_plural': 'Избранные цитаты',
            },
        ),
    ]
