# Generated by Django 5.1 on 2024-10-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_author_alter_subscription_options_alter_note_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, default='Автор неизвестен', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note_author', to='core.author', to_field='name'),
        ),
    ]
