# Generated by Django 5.1 on 2024-10-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecomment',
            name='author',
        ),
        migrations.AddField(
            model_name='notecomment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
    ]
